### Dataset Source:
About this file
Boston House Price dataset




### columns:
* CRIM     per capita crime rate by town
* ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
* INDUS    proportion of non-retail business acres per town
* CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
* NOX      nitric oxides concentration (parts per 10 million)
* RM       average number of rooms per dwelling
* AGE      proportion of owner-occupied units built prior to 1940
* DIS      weighted distances to five Boston employment centres
* RAD      index of accessibility to radial highways
* TAX      full-value property-tax rate per 10,000
* PTRATIO  pupil-teacher ratio by town
* B         where Bk is the proportion of blacks by town
* LSTAT    percentage lower status of the population
* MEDV     Median value of owner-occupied homes in 1000$

### Load Modules

In [1]:
import numpy as np                  # linear algebra python library
import pandas as pd                 # data structure for tabular data.
import matplotlib.pyplot as plt     # visualization library

%matplotlib inline

<br>
Loading data

In [6]:
filename = "housing.csv"
boston_data = pd.read_csv(filename, delim_whitespace=True, header=None)
header = ["CRIM","ZN","INDUS","CHAS","NOX","RM",
          "AGE","DIS","RAD","TAX","PTRATIO","B","LSTAT","MEDV"]

boston_data.columns = header
# display the first 10 rows of dataframe.
boston_data.head(10)

CRIM    ZN  INDUS  CHAS    NOX     RM    AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31     0  0.538  6.575   65.2  4.0900    1  296.0   
1  0.02731   0.0   7.07     0  0.469  6.421   78.9  4.9671    2  242.0   
2  0.02729   0.0   7.07     0  0.469  7.185   61.1  4.9671    2  242.0   
3  0.03237   0.0   2.18     0  0.458  6.998   45.8  6.0622    3  222.0   
4  0.06905   0.0   2.18     0  0.458  7.147   54.2  6.0622    3  222.0   
5  0.02985   0.0   2.18     0  0.458  6.430   58.7  6.0622    3  222.0   
6  0.08829  12.5   7.87     0  0.524  6.012   66.6  5.5605    5  311.0   
7  0.14455  12.5   7.87     0  0.524  6.172   96.1  5.9505    5  311.0   
8  0.21124  12.5   7.87     0  0.524  5.631  100.0  6.0821    5  311.0   
9  0.17004  12.5   7.87     0  0.524  6.004   85.9  6.5921    5  311.0   

   PTRATIO       B  LSTAT  MEDV  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
2     17.8  392.83   4.03  34.7  
3     18.7  394.63   2.94  33.4  
4     18.7  396.90   5.33  36.2  
5     18.7  394.12   5.21  28.7  
6     15.2  395.60  12.43  22.9  
7     15.2  396.90  19.15  27.1  
8     15.2  386.63  29.93  16.5  
9     15.2  386.71  17.10  18.9

<br>
Inspecting variable types

In [8]:
boston_data.dtypes

CRIM       float64
ZN         float64
INDUS      float64
CHAS         int64
NOX        float64
RM         float64
AGE        float64
DIS        float64
RAD          int64
TAX        float64
PTRATIO    float64
B          float64
LSTAT      float64
MEDV       float64
dtype: object

<p class="alert alert-warning">In many datasets, integer variables are cast as float. So, after inspecting
the data type of the variable, even if you get float as output, go ahead
and check the unique values to make sure that those variables are discrete
and not continuous.</p>

### Inspecting all variables
<br>


inspecting distinct values of `RAD`(index of accessibility to radial highways).

In [11]:
boston_data['RAD'].unique()

array([ 1,  2,  3,  5,  4,  8,  6,  7, 24], dtype=int64)

<br>

inspecting distinct values of `CHAS` Charles River dummy variable (= 1 if tract bounds river; 0 otherwise).

In [14]:
boston_data['CHAS'].unique()

array([0, 1], dtype=int64)

<br>

#### inspecting the first 20 distinct values of all continous variables as following:
* CRIM     per capita crime rate by town
* ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
* INDUS    proportion of non-retail business acres per town
* NOX      nitric oxides concentration (parts per 10 million)
* RM       average number of rooms per dwelling
* AGE      proportion of owner-occupied units built prior to 1940
* DIS      weighted distances to five Boston employment centres
* TAX      full-value property-tax rate per 10,000
* PTRATIO  pupil-teacher ratio by town
* B         where Bk is the proportion of blacks by town
* LSTAT    percentage lower status of the population
* MEDV     Median value of owner-occupied homes in 1000$

<br>
CRIM per capita crime rate by town.

In [15]:
boston_data['CRIM'].unique()[0:20]

array([0.00632, 0.02731, 0.02729, 0.03237, 0.06905, 0.02985, 0.08829,
       0.14455, 0.21124, 0.17004, 0.22489, 0.11747, 0.09378, 0.62976,
       0.63796, 0.62739, 1.05393, 0.7842 , 0.80271, 0.7258 ])

<br>
ZN proportion of residential land zoned for lots over 25,000 sq.ft.

In [19]:
boston_data['ZN'].unique()[0:20]

array([ 18. ,   0. ,  12.5,  75. ,  21. ,  90. ,  85. , 100. ,  25. ,
        17.5,  80. ,  28. ,  45. ,  60. ,  95. ,  82.5,  30. ,  22. ,
        20. ,  40. ])

<br>
INDUS proportion of non-retail business acres per town

In [20]:
boston_data['INDUS'].unique()[0:20]

array([ 2.31,  7.07,  2.18,  7.87,  8.14,  5.96,  2.95,  6.91,  5.64,
        4.  ,  1.22,  0.74,  1.32,  5.13,  1.38,  3.37,  6.07, 10.81,
       12.83,  4.86])

<br>
NOX nitric oxides concentration (parts per 10 million)

In [22]:
boston_data['NOX'].unique()[0:20]

array([0.538 , 0.469 , 0.458 , 0.524 , 0.499 , 0.428 , 0.448 , 0.439 ,
       0.41  , 0.403 , 0.411 , 0.453 , 0.4161, 0.398 , 0.409 , 0.413 ,
       0.437 , 0.426 , 0.449 , 0.489 ])

<br>
RM average number of rooms per dwelling

In [24]:
boston_data['RM'].unique()[0:20]

array([6.575, 6.421, 7.185, 6.998, 7.147, 6.43 , 6.012, 6.172, 5.631,
       6.004, 6.377, 6.009, 5.889, 5.949, 6.096, 5.834, 5.935, 5.99 ,
       5.456, 5.727])

<br>
AGE proportion of owner-occupied units built prior to 1940

In [26]:
boston_data['AGE'].unique()[0:20]

array([ 65.2,  78.9,  61.1,  45.8,  54.2,  58.7,  66.6,  96.1, 100. ,
        85.9,  94.3,  82.9,  39. ,  61.8,  84.5,  56.5,  29.3,  81.7,
        36.6,  69.5])

<br>
DIS weighted distances to five Boston employment centres

In [28]:
boston_data['DIS'].unique()[0:20]

array([4.09  , 4.9671, 6.0622, 5.5605, 5.9505, 6.0821, 6.5921, 6.3467,
       6.2267, 5.4509, 4.7075, 4.4619, 4.4986, 4.2579, 3.7965, 3.7979,
       4.0123, 3.9769, 4.0952, 4.3996])

<br>
TAX full-value property-tax rate per 10,000

In [31]:
boston_data['TAX'].unique()[0:20]

array([296., 242., 222., 311., 307., 279., 252., 233., 243., 469., 226.,
       313., 256., 284., 216., 337., 345., 305., 398., 281.])

<br>
PTRATIO pupil-teacher ratio by town

In [32]:
boston_data['PTRATIO'].unique()

array([15.3, 17.8, 18.7, 15.2, 21. , 19.2, 18.3, 17.9, 16.8, 21.1, 17.3,
       15.1, 19.7, 18.6, 16.1, 18.9, 19. , 18.5, 18.2, 18. , 20.9, 19.1,
       21.2, 14.7, 16.6, 15.6, 14.4, 12.6, 17. , 16.4, 17.4, 15.9, 13. ,
       17.6, 14.9, 13.6, 16. , 14.8, 18.4, 19.6, 16.9, 20.2, 15.5, 18.8,
       22. , 20.1])

<br>
B where Bk is the proportion of blacks by town

In [35]:
boston_data['B'].unique()[0:20]

array([396.9 , 392.83, 394.63, 394.12, 395.6 , 386.63, 386.71, 392.52,
       390.5 , 380.02, 395.62, 386.85, 386.75, 288.99, 390.95, 376.57,
       392.53, 394.54, 394.33, 303.42])

<br>
LSTAT percentage lower status of the population

In [37]:
boston_data['LSTAT'].unique()[0:20]

array([ 4.98,  9.14,  4.03,  2.94,  5.33,  5.21, 12.43, 19.15, 29.93,
       17.1 , 20.45, 13.27, 15.71,  8.26, 10.26,  8.47,  6.58, 14.67,
       11.69, 11.28])

<br>
MEDV Median value of owner-occupied homes in 1000$

In [38]:
boston_data['MEDV'].unique()[0:20]

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 13.6, 19.6])

<p class="alert alert-info" role="alert">after we checked the dat type of each variable. we have 2 discrete numerical variable and 10 floating or continuous variales.</p>

#### To understand wheather a variable is contious or discrete. we can also make a histogram for each:
* CRIM     per capita crime rate by town
* ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
* INDUS    proportion of non-retail business acres per town
* NOX      nitric oxides concentration (parts per 10 million)
* RM       average number of rooms per dwelling
* AGE      proportion of owner-occupied units built prior to 1940
* DIS      weighted distances to five Boston employment centres
* TAX      full-value property-tax rate per 10,000
* PTRATIO  pupil-teacher ratio by town
* B         where Bk is the proportion of blacks by town
* LSTAT    percentage lower status of the population
* MEDV     Median value of owner-occupied homes in 1000$